spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: false

logging:
  level:
    root: WARN

springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
