logging:
  level:
    org.hibernate.orm.connections.pooling: WARN

server:
  port: ${APP_PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
