server:
  port: ${PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: application/json,text/plain,text/html
    min-response-size: 1KB
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:200}
      min-spare: ${SERVER_TOMCAT_THREADS_MIN_SPARE:10}
    connection-timeout: ${SERVER_TOMCAT_CONNECTION_TIMEOUT:5s}

spring:
  application:
    name: agencia-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  mvc:
    problemdetails:
      enabled: true
  web:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: false
      max-age: 3600
  jpa:
      open-in-view: false

  sql.init.mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true




management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.hibernate.SQL: ${LOG_SQL_LEVEL:OFF}
    org.hibernate.orm.jdbc.bind: ${LOG_SQL_BIND:OFF}
